image_cropper/config/routes.rb
Rails.application.routes.draw do

  namespace :cropper do
    resources :projects do
      resources :project_images do
        resources :project_crop_images
      end
    end
  end

  namespace :admin do
    resources :users do
      resources :project_users
    end
  end

  namespace :uploader do
   resources :tags
   resources :projects do
     resources :project_users
     resources :project_images
     resources :project_crop_images
   end
  end

  devise_for :users

  devise_scope :user do
    post "users/password" => "devise/passwords#create", as: "password"
    get "users/password/new" => "devise/passwords#new", as: "new_password"
    get "users/password/edit" => "devise/passwords#edit", as: "edit_password"
  end

  get 'site/index'

  root 'site#index'

end

image_cropper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageCropper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand" href="#">Image Cropper</span>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <%= nav_link 'Home', root_path %>
            <% if user_signed_in? %>
              <% if current_user.role_id == 1 || current_user.role_id == 2 %>
                <%= nav_link 'Projects', uploader_projects_path %>
                <%= nav_link 'Tags', uploader_tags_path %>
              <% elsif current_user.role_id == 3 %>
                  <%= nav_link 'Projects', cropper_projects_path %>
              <% end %>
              <% if current_user.role_id == 1 %>
                <%= nav_link 'User Management', admin_users_path %>
              <% end %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right" style="margin-right:5px;">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <%= nav_link 'Edit Profile', edit_user_registration_path(current_user) %>
                  <%= nav_link 'Sign Out', destroy_user_session_path, method: :delete %>
                </ul>
              </li>
            <% else %>
                <%= nav_link 'Sign In', new_user_session_path %>
            <% end %>
          </ul>
        </div>
      </nav>

      <div class="row messages">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
              <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
          <% end %>
        <% end %>
      </div>

      <%= yield %>

      <br/><br/>
  </div>
</body>
</html>