image_cropper/config/routes.rb
Rails.application.routes.draw do

  namespace :cropper do
    resources :projects do
      resources :project_images do
        resources :project_crop_images
      end
    end
  end

  namespace :admin do
    resources :users do
      resources :project_users
    end
  end

  namespace :uploader do
   resources :tags
   resources :projects do
     resources :project_users
     resources :project_images
     resources :project_crop_images
   end
  end

  devise_for :users

  devise_scope :user do
    post "users/password" => "devise/passwords#create", as: "password"
    get "users/password/new" => "devise/passwords#new", as: "new_password"
    get "users/password/edit" => "devise/passwords#edit", as: "edit_password"
  end

  get 'site/index'

  root 'site#index'

end

image_cropper/app/models/user.rb
class User < ActiveRecord::Base
  include SentientUser
  has_many :users
  has_many :project_users, dependent: :destroy
  has_many :project_crop_images, dependent: :destroy
  belongs_to :role
  devise :database_authenticatable, :registerable, :trackable, :recoverable, :validatable
  validates_uniqueness_of :email
  validates_presence_of :name

  def initials
    name.split(/[\s\.]+/).collect { |s| s[0] }.join
  end

  def is_admin?
    role.name.downcase == 'admin'
  end

  def is_uploader?
    role.name.downcase == 'uploader'
  end

end

image_cropper/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_projects, only: [:show]

  def index
    @users = User.where("id <> ?", current_user.id).order(:role_id, :name)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user, user_params[:password]).deliver_later
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render :index, status: :created, location: admin_users_path }
      else
        format.html { render :new }
        format.json { render json: [:admin,@user].errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { render json: { success: true }, status: :accepted, location: admin_users_path }
      else
        format.html { render :edit }
        format.json { render json: [:admin,@user].errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_projects
    @projects = Project.where("isactive = ?",  true).order(:name)
  end

  def user_params
    if !params[:id]
      #@password = 'admin_1234'#(0...8).map { ('a'..'z').to_a[rand(26)] }.join
      params[:user][:password] = 'admin_1234'
      params.require(:user).permit(:name, :email, :password, :is_active, :role_id)
    else
      params.require(:user).permit(:name, :email, :password, :is_active, :role_id)
    end
  end
end

image_cropper/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

image_cropper/app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "form-control width-400", :placeholder => "Firstname Lastname", autofocus: true, :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, :class => "form-control width-400", :placeholder => "Email", :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :role_id, "Role" %><br>
    <%= f.collection_select :role_id, Role.order(:id), :id, :name, {}, {:class => "form-control width-200"} %>
  </div>
  <div class="form-group">
    <%= f.label :is_active, "Isactive" %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
    &nbsp;&nbsp;
    <%= link_to "Back", :back, :class => "btn btn-primary", :type => "button" %>
  </div>
<% end %>

image_cropper/app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Editing User</h2>
    <hr/>
    <%= render 'form' %>
  </div>
</div>

image_cropper/app/views/admin/users/index.html.erb
<h2>User Lists</h2>
<hr/>
<% if @users.size == 0 %>
  <div class="text-center">
    <em>No user data</em>
  </div>
  <br/>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Role</th>
      <th class="text-center"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="user_name"><%= user.name %></td>
        <td class="text-center"><%= user.email %></td>
        <td class="text-center"><%= user.role.name %></td>
        <td class="text-center">
          <%= link_to admin_user_path(user, user: {is_active: !user.is_active}), id: "activate_user_#{user.id}", method: :put, data: { confirm: 'Are you sure to activate/deactivate this user?' } do %>
            <% if user.is_active %>
                <i class="fa fa-check"></i>
            <% else %>
              <i class="fa fa-times"></i>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if user.role_id == 3 %>
            <%= link_to 'Assign', admin_user_path(user), :id => "assign_user_#{user.id}", target: "_top" %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_admin_user_path(user), :id => "edit_user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<%= link_to 'New User', new_admin_user_path, :class => "btn btn-primary", :type => "button" %>

image_cropper/app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Editing Project</h2>
    <hr/>
    <%= render 'form' %>
  </div>
</div>

image_cropper/app/views/admin/users/show.html.erb
<h2>Assign Project to user</h2>
<hr/>
<div class="row">
  <div class="col-md-1">
    <strong>Name: </strong>
  </div>
  <div id="divName" class="col-md-11">
    <%= @user.name %>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <strong>Email: </strong>
  </div>
  <div id="divEmail" class="col-md-11">
    <%= @user.email %>
  </div>
</div>
<%= link_to 'Back', :back, :class => "btn btn-primary", :type => "button" %>