image_cropper/config/routes.rb
Rails.application.routes.draw do

  namespace :cropper do
    resources :projects do
      resources :project_images do
        resources :project_crop_images
      end
    end
  end

  namespace :admin do
    resources :users do
      resources :project_users
    end
  end

  namespace :uploader do
   resources :tags
   resources :projects do
     resources :project_users
     resources :project_images
     resources :project_crop_images
   end
  end

  devise_for :users

  devise_scope :user do
    post "users/password" => "devise/passwords#create", as: "password"
    get "users/password/new" => "devise/passwords#new", as: "new_password"
    get "users/password/edit" => "devise/passwords#edit", as: "edit_password"
  end

  get 'site/index'

  root 'site#index'

end

image_cropper/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :project_images, dependent: :destroy
  has_many :project_users, dependent: :destroy
  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags
  has_many :users, through: :project_users

  attr_accessor :images
  attr_reader :tag_tokens

  validates_presence_of :name
  validates_uniqueness_of :name
  validates :name, format: { with: /\A[a-zA-Z0-9]+\z/,
                                    message: "only allows letters and numbers" }
  track_who_does_it :creator_foreign_key => "user_id", :updater_foreign_key => "user_id"

  def tag_tokens=(ids)
    self.tag_ids = ids.split(',')
  end

  def pretty_tags
    self.tags.collect(&:name).sort.to_sentence
  end

  def fixed_num_crop_points
    return self.crop_points > 0
  end

  def crop_instructions
    "Please select objects of type #{self.pretty_tags} with " +
      (self.fixed_num_crop_points ? "exactly #{self.crop_points} points. " : "any number of points. ") + "points. " +
      (self.fixed_num_crop_points ? "Press ENTER after you're finished with an object. " : "") +
      "Right click and select Delete to remove a selection."
  end

end

image_cropper/app/controllers/cropper/projects_controller.rb
class Cropper::ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @project_ids = []
    ProjectUser.where("user_id=?",current_user.id).each { |project| @project_ids.push(project.project_id) }
    @projects = Project.where(id: @project_ids).order(:name)
  end

end

image_cropper/app/controllers/uploader/project_crop_images_controller.rb
class Uploader::ProjectCropImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_uploader
  before_action :set_project

  def index
  end

  def destroy
    @project_crop_image = ProjectCropImage.find(params[:id]).destroy
    remove_crop_image
    respond_to do |format|
      format.html { redirect_to uploader_project_project_crop_images_path(@project), notice: 'Cropped image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def remove_crop_image
    @file_path = "#{Rails.root.to_s}/public/system/projects/#{@project.name}/#{@project_crop_image.user_id.to_s}/#{@project_crop_image.image}"
    system("rm #{@file_path}")
  end

end

image_cropper/app/controllers/uploader/project_images_controller.rb
class Uploader::ProjectImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_uploader
  before_action :set_project, :set_project_image, only: [:destroy]
  after_action :destroy_image, only: [:destroy]

  def destroy
    @project_image.destroy
    respond_to do |format|
      format.html { redirect_to [:edit, :uploader, @project], notice: 'Project Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_project_image
    @project_image = ProjectImage.find(params[:id])
  end

  def destroy_image
    file_path = "#{Rails.root.to_s}/public/system/projects/#{@project.name}"
    system("rm #{file_path}/#{@project_image.image}")
  end

end

image_cropper/app/controllers/uploader/project_users_controller.rb
class Uploader::ProjectUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_uploader
  before_action :set_project
  before_action :set_project_user, only: [:update, :destroy]

  def index
    @users = User.all.sort_by(&:name)
  end

  def create
    @project_user = ProjectUser.new(project_user_params)
    respond_to do |format|
      if @project_user.save
        format.html { redirect_to uploader_project_project_users_path(params[:project_id]), notice: 'User was successfully assigned to the project.' }
        format.json { render json: { delete_path: uploader_project_project_user_path(project_id: @project.id, id: @project_user.id, format: :json) }, status: :created }
      else
        format.html { render :new }
        format.json { render json: @project_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project_user.update(project_user_params)
        format.html { redirect_to uploader_project_project_users_path(params[:project_id]), notice: 'User was successfully updated for the project' }
        format.json { render json: { success: true }, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @project_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    user = @project_user.user
    @project_user.destroy
    respond_to do |format|
      format.html { redirect_to uploader_project_project_users_path(params[:project_id]), notice: 'User was successfully unassigned to the project.' }
      format.json { render json: { create_path: uploader_project_project_users_path(project_id: @project.id, project_user: {user_id: user.id, project_id: @project.id}, format: :json) }, status: :ok }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_project_user
    @project_user = ProjectUser.find(params[:id])
  end

  def project_user_params
    params.require(:project_user).permit(:user_id, :project_id, :tag_id)
  end
end

image_cropper/app/controllers/uploader/projects_controller.rb
require 'zip'

class Uploader::ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_uploader
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.order(:name)
  end

  def show
    respond_to do |format|
      format.zip do
        zipfile = make_zip_file(@project)
        send_file zipfile.path, filename: "#{@project.name}.zip"
      end
      format.html
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        manage_directory
        format.html { redirect_to [:uploader,@project], notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: [:uploader,@project] }
      else
        format.html { render :new }
        format.json { render json: [:uploader,@project].errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        manage_directory
        format.html { redirect_to [:uploader,@project], notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: [:uploader,@project] }
      else
        format.html { render :edit }
        format.json { render json: [:uploader,@project].errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    destroy_images()
    respond_to do |format|
      format.html { redirect_to uploader_projects_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
    @project_name = @project.name
  end

  def manage_directory
    if !params[:id]
      file_path = File.join(Rails.application.config.projects_dir, @project.name)
      Dir.mkdir(file_path) unless Dir.exist?(file_path)
      unzip_images(file_path)
    else
      old_file_path = File.join(Rails.application.config.projects_dir, @project_name)
      current_file_path = File.join(Rails.application.config.projects_dir, @project.name)
      if old_file_path != current_file_path and File.directory?(old_file_path)
        system("rm -rf #{current_file_path}")
        system("mv #{old_file_path} #{current_file_path}")
      end
      unzip_images(current_file_path)
    end
  end

  def unzip_images(file_path)
    if project_params[:images]
      if(File.extname("#{project_params[:images].original_filename}") == ".zip")
        Zip::File.open("#{project_params[:images].path}") do |zipfile|
          zipfile.each do |file|
            this_file_path = "#{file_path}/#{file}"
            zipfile.extract(file, this_file_path) unless File.exist?(this_file_path)
            mimetype = FileMagic.open(:mime) { |fm| fm.file(this_file_path) }
            if mimetype.start_with? 'image'
              dims = Dimensions.dimensions(this_file_path)
              ProjectImage.create(project_id: @project.id, image: file, w: dims[0], h: dims[1])
            end
          end
        end
      else
        file_name = project_params[:images].original_filename
        path = "#{file_path}/#{file_name}"
        File.open(path, 'wb') do |file|
          file.write(project_params[:images].read)
        end
        dims = Dimensions.dimensions(path)
        ProjectImage.create(project_id: @project.id, image: file_name, w: dims[0], h: dims[1])
      end
    end
  end

  def destroy_images
    if params[:id]
      file_path = "#{Rails.root.to_s}/public/system/projects/#{@project.name}"
      @project.project_images.destroy
      if File.directory?(file_path)
        system("rm -rf #{file_path}")
      end
    end
  end

  def project_params
    params.require(:project).permit(:name, :description, :images, :crop_points, :isactive, :rectangle_thickness, :tag_tokens)
  end

  def make_cnn_file(project_image)
    outfile = Tempfile.new('foo')
    project_image.project_crop_images.each do |pci|
      outfile.write "#{pci.cnn_data}\n"
    end
    outfile.close
    filename = project_image.image.gsub(/\//, '-')
    if filename =~ /\.[A-Za-z].*$/
      filename.gsub!(/\.[A-Za-z].*$/, '.txt')
    else
      filename = "#{filename}.txt"
    end
    return outfile, filename
  end

  def make_yml_file(project)
    outfile = Tempfile.new('foo')
    outfile.write "%YAML:1.0\n"
    outfile.write "version: 4\n"
    outfile.write "project: #{project.name}\n"
    outfile.write "hasVaryingImageSizes: 1\n"
    outfile.write "startFrameNo: 0\n"
    project.project_images.each_with_index do |pi, i|
      outfile.write "frame#{i}:\n"
      outfile.write "  width: #{pi.w}\n"
      outfile.write "  height: #{pi.h}\n"
      outfile.write "  imageName: #{pi.image}\n"
      pi.project_crop_images.each_with_index do |pci, j|
        outfile.write "  region#{j}:\n"
        outfile.write "    numPts: #{pci.project_crop_image_cords.size}\n"
        outfile.write "    matPts: !!opencv-matrix\n"
        outfile.write "      rows: #{pci.project_crop_image_cords.size}\n"
        outfile.write "      cols: 2\n"
        outfile.write "      dt: f\n"
        outfile.write "      data: ["
        n = pci.project_crop_image_cords.size
        pci.project_crop_image_cords.each_with_index do |coord, k|
          outfile.write " #{coord.x}, #{coord.y}#{k == n-1 ? "" : "," }"
        end
        outfile.write " ]\n"
        outfile.write "    attribute: #{pci.tag.name}\n"
      end
      outfile.write "  numValidRegions: #{pi.project_crop_images.size}\n"
    end
    outfile.write "endFrameNo: #{project.project_images.length-1}\n"
    outfile.close
    return outfile
  end

  def make_zip_file(project)
    tempfile = Tempfile.new("zip")
    # Add temp files to this list to prevent their garbage collection before the ZIP file is finished
    tempfiles = []
    Zip::File.open(tempfile.path, Zip::File::CREATE) do |zip_file|
      yml_file = make_yml_file(project)
      tempfiles << yml_file
      zip_file.add("#{project.name}/#{project.name}.yml", yml_file.path)
      project.project_images.each do |pi|
        next unless pi.project_crop_images.size > 0
        path = File.join(Rails.application.config.projects_dir, project.name, pi.image)
        zip_file.add("#{project.name}/original/#{pi.image}", path)
        cnn_file, cnn_filename = make_cnn_file(pi)
        tempfiles << cnn_file
        zip_file.add("#{project.name}/CNN/#{cnn_filename}", cnn_file.path)
        pi.project_crop_images.each do |pci|
          path = File.join(Rails.application.config.projects_dir, project.name, pci.user_id.to_s, pci.image)
          zip_file.add("#{project.name}/crops/#{pci.user_id}/#{pci.image}", path)
        end
      end
    end
    return tempfile
  end

end

image_cropper/app/controllers/uploader/tags_controller.rb
require 'zip'
class Uploader::TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_uploader
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.where("name like ?", "%#{params[:q]}%").order(:name)
    respond_to do |format|
      format.html
      format.json do
        render json: @tags
      end
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to uploader_tags_path, notice: 'Tag was successfully created.' }
        format.json { render :index, status: :created, location: uploader_tags_path }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to uploader_tags_path, notice: 'Tag was successfully updated.' }
        format.json { render :index, status: :ok, location: uploader_tags_path}
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to uploader_tags_path, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
    @tag_name = @tag.name
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

image_cropper/app/helpers/cropper/projects_helper.rb
module Cropper::ProjectsHelper
end

image_cropper/app/helpers/uploader/project_crop_images_helper.rb
module Uploader::ProjectCropImagesHelper
end

image_cropper/app/helpers/uploader/project_images_helper.rb
module Uploader::ProjectImagesHelper
end

image_cropper/app/helpers/uploader/project_users_helper.rb
module Uploader::ProjectUsersHelper
end

image_cropper/app/helpers/uploader/projects_helper.rb
module Uploader::ProjectsHelper
end

image_cropper/app/helpers/uploader/tags_helper.rb
module Uploader::TagsHelper
end

image_cropper/app/views/uploader/projects/_form.html.erb
<%= form_for([:uploader, @project], class: "form-inline") do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control width-300", :placeholder => "Project name", :pattern => "[a-zA-Z0-9]+", :title => "Not allow to use space or any special characters", :required => true, :autofocus => true %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control width-600", :placeholder => "Description" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_tokens, 'Tags' %>
    <%= f.text_field :tag_tokens, data: {load: @project.tags} %>
  </div>

  <div class="form-group">
    <%= f.label :images %>&nbsp;&nbsp;<em>Please upload with .zip or any image file</em><br>
    <%= f.file_field :images %>
    <% if params[:id] %>
      <br/>
      <table class="table table-striped">
        <tbody>
          <% @project.project_images.all.each do |project_image| %>
            <tr>
              <td class="width-100"><%= image_tag "/system/projects/#{@project.name}/#{project_image.image}", :height => 50 %></td>
              <td  class="width-200"><%= project_image.image %></td>
              <td><%= link_to 'Destroy', uploader_project_project_image_path(@project, project_image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :crop_points %>&nbsp;&nbsp;<em>(The number of points needed to specify a crop)</em><br>
    <% @options = [["1", "1"], ["2", "2"], ["4", "4"], ["N", "0"]] %>
    <%= f.select :crop_points, [["1 Point", "1"], ["2 Points", "2"], ["4 Points", "4"], ["N Points", "0"]], {}, {:class => "form-control width-200"} %>
  </div>

  <div class="form-group">
    <%= f.label :isactive %>
    <%= f.check_box :isactive %>
  </div>

  <div class="form-group">
    <%= f.label :rectangle_thickness %> <em>(The thickness of the bounding rectangles shown in the crop display)</em><br>
    <%= f.text_field :rectangle_thickness %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>&nbsp;&nbsp;
    <%= link_to 'Cancel', uploader_projects_path, :class => "btn btn-primary", :type => "button" %>
  </div>

<% end %>

image_cropper/app/views/uploader/projects/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Editing Project</h2>
    <hr/>
    <%= render 'form' %>
  </div>
</div>

image_cropper/app/views/uploader/projects/index.html.erb
<h2>Project List</h2>
<hr/>
<% if @projects.size == 0 %>
  <div class="text-center">
    <em>No project data</em>
  </div>
  <br/>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th class="text-center">Points per crop</th>
      <th class="text-center">Active?</th>
      <th class="text-center">Owner</th>
      <th class="text-center">Thickness</th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class="project_name"><%= project.name %></td>
        <td class="text-center"><%= project.crop_points %></td>
        <td class="text-center">
          <% if project.isactive %>
            <i class="fa fa-check"></i>
          <% else %>
            <i class="fa fa-times"></i>
          <% end%>
        </td>
        <td class="text-center"><%= project.user.name %></td>
        <td class="text-center"><%= project.rectangle_thickness %></td>
        <td><%= link_to 'Show details', [:uploader,project] %></td>
        <td><%= link_to 'Assign users', [:uploader,project,'project_users'], id: "assign_project_#{project.id}", target: "_top" %></td>
        <td><%= link_to 'Show cropped images', [:uploader,project,'project_crop_images'], id: "project_crop_images_#{project.id}", target: "_top" %></td>
        <td><%= link_to 'Download images', uploader_project_path(id: project.id, format: :zip) %></td>
        <% if current_user.id == project.user_id || current_user.role_id == 1 %>
          <td><%= link_to 'Edit', edit_uploader_project_path(project), :id => "edit_project_#{project.id}" %></td>
          <td><%= link_to 'Destroy', [:uploader,project], method: :delete, data: { confirm: 'Are you sure?' }, :id => "delete_project_#{project.id}" %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<%= link_to 'New Project', new_uploader_project_path, :class => "btn btn-primary", :type => "button" %>

image_cropper/app/views/uploader/projects/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>New Project</h2>
    <hr/>
    <%= render 'form' %>
  </div>
</div>

image_cropper/app/views/uploader/projects/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Project Information</h2>
    <hr/>
    <div class="row">
      <div class="col-md-2"><strong>Project Name: </strong></div>
      <div id="project_name" class="col-md-10"><%= @project.name %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Description: </strong></div>
      <div id="project_description" class="col-md-10"><%= @project.description %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Tags:</strong></div>
      <div id="project_tags" class="col-md-10"><%= @project.tags.collect(&:name).sort.join(', ') %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Crop Points: </strong></div>
      <div id="project_crop_points" class="col-md-10"><%= @project.crop_points %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Active: </strong></div>
      <div id="project_isactive" class="col-md-10"><%= @project.isactive %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Project Owner: </strong></div>
      <div id="project_user" class="col-md-10"><%= @project.user.name %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Rectangle Thickness: </strong></div>
      <div id="thickness" class="col-md-10"><%= @project.rectangle_thickness %></div>
    </div>
  </div>
</div>
<br/>
<% if @project.project_images.size == 0 %>
  <div class="text-center">
    <em>No Image in this project</em>
  </div>
  <br/>
<% else %>
  <table class="table table-striped">
    <tbody>
      <% @project.project_images.all.each do |project_image| %>
        <tr>
          <td class="width-100"><%= image_tag "/system/projects/#{@project.name}/#{project_image.image}", :height => 50 %></td>
          <td><%= project_image.image %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br/>
<h2>Users in Project</h2>
<hr/>
<%= link_to "Add more user", [:uploader,@project,'project_users'], class: "btn btn-primary", target: "_blank" %>
<% if @project.project_users.size == 0 %>
  <div class="text-center">
    <p>No user in this project</p>
  </div>
  <br/>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <td class="width-50 text-bold">No</td>
        <td class="text-bold">Firstname Lastname</td>
        <td class="text-bold">Email</td>
      </tr>
    </thead>
    <tbody>
      <% row = 1 %>
      <% @project.project_users.all.each do |project_user| %>
        <tr>
          <td class="width-50"><%= row %></td>
          <td class="width-300"><%= project_user.user.name %></td>
          <td><%= project_user.user.email %></td>
        </tr>
        <% row += 1 %>
      <% end %>
    </tbody>
  </table>
<% end %>
<br/>
<% if current_user.id == @project.user_id %>
  <%= link_to 'Edit', edit_uploader_project_path(@project), :class => "btn btn-primary", :type => "button" %>
  &nbsp;&nbsp;
<% end %>
<%= link_to 'Back', uploader_projects_path, :class => "btn btn-primary", :type => "button" %>